test:Test pipeline-v3

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -42,9 +42,10 @@ jobs:
         run: vendor/bin/phpunit tests
 
   
-  deploy:
+  deploy_to_staging:
     name: Deploy to Azure Container Apps
     runs-on: ubuntu-latest
+    needs: build
 
     steps:
       - name: Checkout Code
@@ -83,13 +84,63 @@ jobs:
             --image swe40006.azurecr.io/mysql-db:latest \
             --set-env-vars "MYSQL_ROOT_PASSWORD=2611" "MYSQL_DATABASE=my_friend_system" "MYSQL_USER=myuser" "MYSQL_PASSWORD=mypassword"
           
+
+  integration_testing:
+    name: Run integration test on staging
+    runs-on: ubuntu-latest
+    environment: staging
+    needs: deploy_to_staging
+    steps:
+      - name: Get Staging URL
+        run: |
+          STAGING_URL=$(az containerapp show \
+            --name php-app-staging \
+            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
+            --query properties.configuration.ingress.fqdn \
+            --output tsv)
+          echo "STAGING_URL=http://$STAGING_URL" >> $GITHUB_ENV
+
+      - name: Run Basic Integration Tests
+        run: |
+          echo "Testing Homepage..."
+          curl --fail $STAGING_URL || exit 1
+          
+          echo "Checking if the homepage works as expectation..."
+          curl -s $STAGING_URL | grep -Eqi "My Friend System" || { echo "ERROR: 'My Friend System' not found!"; exit 1; }
+          curl -s $STAGING_URL | grep -Eqi "Assignment Homepage" || { echo "ERROR: 'Assignment Homepage' not found!"; exit 1; }
+          curl -s $STAGING_URL | grep -Eqi "Huy Vu Tran" || { echo "ERROR: 'Huy Vu Tran' not found!"; exit 1; }
+
+  deploy_to_production:
+    name: Deploy to Production
+    runs-on: ubuntu-latest
+    needs: integration_testing
+    environment: production
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+
+      - name: Log in to Azure
+        uses: azure/login@v1
+        with:
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
+
+      - name: Build & Push Production PHP App Image
+        run: |
+          docker build -t swe40006.azurecr.io/my_friend_system-php-app-production:latest .
+          docker push swe40006.azurecr.io/my_friend_system-php-app-production:latest
+
+      - name: Deploy to Azure Container Apps for prod pupose
+        run: |
+          az containerapp update \
+            --name php-app \
+            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
+            --image swe40006.azurecr.io/my_friend_system-php-app:latest \
+            --set-env-vars "DB_HOST=mysql-db" "DB_NAME=my_friend_system" "DB_USER=myuser" "DB_PASS=mypassword"
+
           az containerapp revision restart \
             --name php-app \
             --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
             --revision ${{ secrets.REVISION_NAME }}
-
-
-  #Improvement: Monitor + two separate environment testing and prod (after running pipeline(test server) #=> integration test if passed => prod server)
     
     
     
